# Site settings
title: Malek Atwiz - Personal blog
description: Personal technical blog for Malek Atwiz, a software developer works with .NET technologies

# User settings
username: Malek Atwiz
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: Software Developer
email: malek.atwiz@hotmail.com
github_username:  malekatwiz

# Google-analytics
google-analytics:
  id: "UA-69684210-2"

exclude: ['package.json', 'src' , 'node_modules']

theme: jekyll-theme-cayman